### ISSUE TITLE
Erreur au lancement

### ISSUE THREAD

**Issue by ghost** [tontof/kriss_blog#6]
Bonjour,

je veux essayer kriss_blog mais j'ai cette erreur au dessus du formulaire d'installation:

> Strict Standards: Non-static method BlogPage::init() should not be called statically, assuming $this from incompatible context in xxxxx/index.php on line 125

Je tient à preciser que ca fontionne tres bien apres !

**Comment by emporeso2** [comment]
capture 
![Uploading kriss_blog_bug.jpg…]()

**Comment by tontof** [comment]
C'est corrigé. Il manquait un static sur une fonction !
Merci bien
